/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/muschi.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/muschi.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Musle_Fiber_Armature">
          <primitive object={nodes.Bone} />
          <group name="musclefibermodel">
            <skinnedMesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Muscle no Texture']} skeleton={nodes.Cylinder004.skeleton} />
            <skinnedMesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials['Muscle Inside']} skeleton={nodes.Cylinder004_1.skeleton} />
          </group>
        </group>
        <group name="IzoArmRig">
          <primitive object={nodes.mixamorig1LeftShoulder} />
          <primitive object={nodes.elbowIK} />
          <primitive object={nodes.handIK} />
          <skinnedMesh name="izomodel" geometry={nodes.izomodel.geometry} material={materials.Skin} skeleton={nodes.izomodel.skeleton} />
        </group>
        <group name="MetricArmRig">
          <primitive object={nodes.mixamorig1LeftShoulder_1} />
          <primitive object={nodes.elbowIK_1} />
          <primitive object={nodes.handIK_1} />
          <skinnedMesh name="metricmodel" geometry={nodes.metricmodel.geometry} material={materials['Material.001']} skeleton={nodes.metricmodel.skeleton} />
        </group>
        <group name="ExcentricArmRig">
          <primitive object={nodes.mixamorig1LeftShoulder_2} />
          <primitive object={nodes.elbowIK_2} />
          <primitive object={nodes.handIK_2} />
          <skinnedMesh name="excentricarmmodel" geometry={nodes.excentricarmmodel.geometry} material={materials['Material.002']} skeleton={nodes.excentricarmmodel.skeleton} />
        </group>
        <group name="NerveArmRig" rotation={[-Math.PI, 0, 0]} scale={-1}>
          <primitive object={nodes.mixamorig1LeftShoulder_3} />
          <primitive object={nodes.elbowIK_3} />
          <primitive object={nodes.handIK_3} />
          <skinnedMesh name="nervearmmodel" geometry={nodes.nervearmmodel.geometry} material={materials['Material.003']} skeleton={nodes.nervearmmodel.skeleton} />
        </group>
        <group name="Nerve_Path" rotation={[-Math.PI, 0, 0]} scale={-1} />
        <group name="ForceArmRig" position={[5.013, -0.104, 0]} rotation={[0, Math.PI / 2, 0]} scale={1.841}>
          <primitive object={nodes.mixamorig1LeftShoulder_4} />
          <primitive object={nodes.elbowIK_4} />
          <primitive object={nodes.handIK_4} />
          <group name="forcearmmodel">
            <skinnedMesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials['Skin.001']} skeleton={nodes.Mesh004.skeleton} />
            <skinnedMesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials['Muscle no Texture.001']} skeleton={nodes.Mesh004_1.skeleton} />
            <skinnedMesh name="Mesh004_2" geometry={nodes.Mesh004_2.geometry} material={materials['Muscle Inside.001']} skeleton={nodes.Mesh004_2.skeleton} />
            <skinnedMesh name="Mesh004_3" geometry={nodes.Mesh004_3.geometry} material={materials['Skin Inside']} skeleton={nodes.Mesh004_3.skeleton} />
          </group>
        </group>
        <group name="Skeletal_Muscle" position={[-3, 0, 0]}>
          <mesh name="skeletalmuscle" geometry={nodes.skeletalmuscle.geometry} material={materials.Muscle} />
          <mesh name="skeletalmuscle_1" geometry={nodes.skeletalmuscle_1.geometry} material={materials.Rock} />
          <mesh name="skeletalmuscle_2" geometry={nodes.skeletalmuscle_2.geometry} material={materials.NODISPLAY} />
        </group>
        <group name="Cardiac_Muscles">
          <mesh name="cardiacmuscle" geometry={nodes.cardiacmuscle.geometry} material={materials.Muscle} />
          <mesh name="cardiacmuscle_1" geometry={nodes.cardiacmuscle_1.geometry} material={materials.Rock} />
          <mesh name="cardiacmuscle_2" geometry={nodes.cardiacmuscle_2.geometry} material={materials.NODISPLAY} />
        </group>
        <group name="Smooth_Muscles" position={[3, 0, 0]}>
          <mesh name="smoothmuscle" geometry={nodes.smoothmuscle.geometry} material={materials['Muscle no Texture']} />
          <mesh name="smoothmuscle_1" geometry={nodes.smoothmuscle_1.geometry} material={materials.Rock} />
          <mesh name="smoothmuscle_2" geometry={nodes.smoothmuscle_2.geometry} material={materials.NODISPLAY} />
        </group>
        <mesh name="BoneForMuscle" geometry={nodes.BoneForMuscle.geometry} material={materials.Bone} />
        <group name="Brain" rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh name="brainmodel" geometry={nodes.brainmodel.geometry} material={materials.Brain} />
          <mesh name="brainmodel_1" geometry={nodes.brainmodel_1.geometry} material={materials.Brain2} />
        </group>
        <mesh name="Nerve" geometry={nodes.Nerve.geometry} material={materials.Nerve} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh name="Impulse" geometry={nodes.Impulse.geometry} material={materials.Impulse} position={[0, 5.167, -0.16]} rotation={[-Math.PI / 4, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/muschi.glb')
