/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/muschi.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/muschi.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Musle_Fiber_Armature">
          <primitive object={nodes.Bone} />
          <group name="musclefibermodel">
            <skinnedMesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Muscle no Texture']} skeleton={nodes.Cylinder004.skeleton} />
            <skinnedMesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials['Muscle Inside']} skeleton={nodes.Cylinder004_1.skeleton} />
          </group>
        </group>
        <group name="Skeletal_Muscle" position={[-3, 0, 0]}>
          <mesh name="skeletalmuscle" geometry={nodes.skeletalmuscle.geometry} material={materials.Muscle} />
          <mesh name="skeletalmuscle_1" geometry={nodes.skeletalmuscle_1.geometry} material={materials.Rock} />
          <mesh name="skeletalmuscle_2" geometry={nodes.skeletalmuscle_2.geometry} material={materials.NODISPLAY} />
        </group>
        <group name="Cardiac_Muscles">
          <mesh name="cardiacmuscle" geometry={nodes.cardiacmuscle.geometry} material={materials.Muscle} />
          <mesh name="cardiacmuscle_1" geometry={nodes.cardiacmuscle_1.geometry} material={materials.Rock} />
          <mesh name="cardiacmuscle_2" geometry={nodes.cardiacmuscle_2.geometry} material={materials.NODISPLAY} />
        </group>
        <group name="Smooth_Muscles" position={[3, 0, 0]}>
          <mesh name="smoothmuscle" geometry={nodes.smoothmuscle.geometry} material={materials['Muscle no Texture']} />
          <mesh name="smoothmuscle_1" geometry={nodes.smoothmuscle_1.geometry} material={materials.Rock} />
          <mesh name="smoothmuscle_2" geometry={nodes.smoothmuscle_2.geometry} material={materials.NODISPLAY} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/muschi.glb')
