/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/arm.glb 
*/

import React from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'

export function MODEL_Arm({ animationTime = 0, ...props }) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/arm.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  
  // Enable backface culling on all materials
  React.useEffect(() => {
    Object.values(materials).forEach(material => {
      if (material) {
        material.side = THREE.FrontSide // Enable backface culling
      }
    })
  }, [materials])
  
  // Set animation time based on prop
  React.useEffect(() => {
    if (actions) {
      const actionNames = Object.keys(actions)
      //console.log('Available animations:', actionNames) // Debug log
      if (actionNames.length > 0) {
        const action = actions[actionNames[0]]
        if (action && action.getClip()) {
          const duration = action.getClip().duration
          const clampedTime = Math.max(0, Math.min(animationTime, duration))
          
          //console.log('Setting animation time:', clampedTime, 'of', duration) // Debug log
          
          // Reset and configure the action
          action.reset()
          action.enabled = true
          action.setLoop(THREE.LoopOnce)
          action.clampWhenFinished = true
          
          // Play, set the time, then immediately pause to freeze
          action.play()
          action.time = clampedTime
          action.paused = true
          
          // Update the mixer to apply changes immediately
          if (action.getMixer()) {
            action.getMixer().update(0)
          }
        }
      }
    }
  }, [actions, animationTime])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Arm_Rig">
          <primitive object={nodes.mixamorig1LeftShoulder} />
          <group name="Model">
            <skinnedMesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.Material} skeleton={nodes.Mesh.skeleton} />
            <skinnedMesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Inside} skeleton={nodes.Mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/arm.glb')

export default MODEL_Arm
