/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/muschi.glb 
*/

import React, { useState } from 'react';
import * as THREE from 'three';
import { Box, OrbitControls, ScrollControls, Scroll, useScroll, Stats, Text, useGLTF, useAnimations} from '@react-three/drei';
import { animated, useSpring} from '@react-spring/three';
import { useGraph } from '@react-three/fiber'
import { SkeletonUtils } from 'three-stdlib'

function NODISPLAYMATERIAL(){
  return new THREE.MeshBasicMaterial({ visible: false });
}

export function MODEL_Muscles(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/muschi.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  const currentPage = props.currentPage || 0;
  
  const [hoveredLeft, setHoveredLeft] = useState(false);
  const [hoveredCenter, setHoveredCenter] = useState(false);
  const [hoveredRight, setHoveredRight] = useState(false);

  // Animate elevation with react-spring
  const leftSpring = useSpring({
    position: [-3, currentPage === 2 && hoveredLeft ? 0.3 : 0, 0],
    scale: currentPage !== 3 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });
  const rightSpring = useSpring({
    position: [3, currentPage === 2 && hoveredRight ? 0.3 : 0, 0],
    scale: currentPage !== 3 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });
  const centerSpring = useSpring({
    position: [0, currentPage === 2 && hoveredCenter ? 0.3 : 0, 0],
    scale: currentPage !== 3 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });
  const muscleFiberSpring = useSpring({
    scale: currentPage === 3 ? 1 : 0,
    config: { mass: 1, tension: 180, friction: 18 }
  });

  return (
    <group {...props} dispose={null}>
      <animated.group
        position={leftSpring.position}
        scale={leftSpring.scale}
        onPointerOver={() => currentPage === 2 && setHoveredLeft(true)}
        onPointerOut={() => setHoveredLeft(false)}
      >
        <mesh geometry={nodes.skeletalmuscle.geometry} material={materials.Muscle} />
        <mesh geometry={nodes.skeletalmuscle_1.geometry} material={materials.Rock} />
        <mesh geometry={nodes.skeletalmuscle_2.geometry} material={NODISPLAYMATERIAL()} />
        
        {hoveredLeft && (
          <Text
          position={[0, 1, 0]}
          fontSize={0.25}
          color="white"
          anchorX="center"
          anchorY="middle"
        >
          scheletici 
        </Text>
        )}
      </animated.group>

      <animated.group
        position={rightSpring.position}
        scale={rightSpring.scale}
        onPointerOver={() => currentPage === 2 && setHoveredRight(true)}
        onPointerOut={() => setHoveredRight(false)}
      >
        <mesh geometry={nodes.smoothmuscle.geometry} material={materials['Muscle no Texture']} />
        <mesh geometry={nodes.smoothmuscle_1.geometry} material={materials.Rock} />
        <mesh geometry={nodes.smoothmuscle_2.geometry} material={NODISPLAYMATERIAL()} />
        
        {hoveredRight && (
        <Text
          position={[0, 1, 0]}
          fontSize={0.25}
          color="white"
          anchorX="center"
          anchorY="middle"
        >
          cardiaci
        </Text>
        )}
      </animated.group>

      <animated.group
        position={centerSpring.position}
        scale={centerSpring.scale}
        onPointerOver={() => currentPage === 2 && setHoveredCenter(true)}
        onPointerOut={() => setHoveredCenter(false)}
      >
        <mesh geometry={nodes.cardiacmuscle.geometry} material={materials.Muscle} />
        <mesh geometry={nodes.cardiacmuscle_1.geometry} material={materials.Rock} />
        <mesh geometry={nodes.cardiacmuscle_2.geometry} material={NODISPLAYMATERIAL()} />
        
        {hoveredCenter && (
        <Text
          position={[0, 1, 0]}
          fontSize={0.25}
          color="white"
          anchorX="center"
          anchorY="middle"
        >
          netezi 
        </Text>
        )}
      </animated.group>
        
      <animated.group name="Musle_Fiber_Armature" scale={muscleFiberSpring.scale}>
        <primitive object={nodes.Bone} />
        <group name="musclefibermodel">
          <skinnedMesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Muscle no Texture']} skeleton={nodes.Cylinder004.skeleton} />
          <skinnedMesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials['Muscle Inside']} skeleton={nodes.Cylinder004_1.skeleton} />
        </group>
      </animated.group>
    </group>
  );
}

useGLTF.preload('./models/muschi.glb')

export default MODEL_Muscles
